### ISSUE TITLE
Hangfire Failed job cleanup 

### ISSUE THREAD

**Issue by hnalpha323** [sbergot/mauffre#1]
Hi ,
First of all , sorry to write this way but I was looking at this 
https://github.com/HangfireIO/Hangfire/issues/1211
I am trying to do something similar where failed jobs cleanup should be done whenever succeeded jobs are cleaned up. 
I was wondering if you had code examples of what you did before.
Any help is appreciated
Thanks
-Hamza

**Comment by sbergot** [comment]
@hnalpha323 I cannot share out code but I shared all the details at the end of the issue you have linked.
